import type React from "react"
import "./globals.css"
import { Inter } from "next/font/google"
import { ToastProvider } from "@/components/toast/toast-provider"
const inter = Inter({ subsets: ["latin"] })
export const metadata = {
  title: "HRM AI",
  description: "Generated by create next app",
  generator: 'GSU25SE03'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body className={inter.className}>
        {/* <Header/> */}
        {children}
        {/* <Footer/> */}
        <ToastProvider />  
      </body>
    </html>
  )
}


