import type React from "react"
import ClientLayout from "./clientLayout"

export const metadata = {
  title: "HRM AI",
  description: "Generated by create next app",
    generator: 'GSU25SE03'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>{children}</ClientLayout>
}


import './globals.css'