import type React from "react"
import ClientLayout from "./clientLayout"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>{children}</ClientLayout>
}


import './globals.css'