import type React from "react"

export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
    generator: 'GSU25SE03'
}

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>{children}</ClientLayout>
}


import '../globals.css'
import ClientLayout from "../clientLayout"
