import { InterviewProcessDetail } from "./interview-process-detail"


// Sample data based on the provided JSON structure
const sampleData = {
  interviewStageModels: [
    {
      stageName: "Vòng 1",
      description: "Phỏng vấn sơ bộ qua điện thoại để đánh giá kỹ năng cơ bản và động lực làm việc của ứng viên",
      order: 1,
      totalTime: 30,
      departmentModel: null,
      interviewTypeModel: null,
      id: "f8042344-7bb3-4e90-d381-08dddffc9a87",
      creationDate: "2025-08-21T15:37:22.3498888Z",
      createdById: null,
      modificationDate: null,
      modifiedById: null,
      deletionDate: null,
      deletedById: null,
      isDeleted: false,
    },
    {
      stageName: "Vòng 2",
      description: "Phỏng vấn chuyên môn trực tiếp với team leader để đánh giá kỹ năng kỹ thuật và kinh nghiệm",
      order: 2,
      totalTime: 60,
      departmentModel: null,
      interviewTypeModel: null,
      id: "fac9788e-0ee8-4b5f-d382-08dddffc9a87",
      creationDate: "2025-08-21T15:37:22.3498932Z",
      createdById: null,
      modificationDate: null,
      modifiedById: null,
      deletionDate: null,
      deletedById: null,
      isDeleted: false,
    },
    {
      stageName: "Vòng 3",
      description: "Phỏng vấn với HR và quản lý cấp cao để đánh giá văn hóa công ty và thương lượng điều kiện",
      order: 3,
      totalTime: 45,
      departmentModel: null,
      interviewTypeModel: null,
      id: "c702e19f-38cc-4b2d-8af7-08dde0ba28f4",
      creationDate: "2025-08-21T15:42:37.2561443Z",
      createdById: null,
      modificationDate: null,
      modifiedById: null,
      deletionDate: null,
      deletedById: null,
      isDeleted: false,
    },
    {
      stageName: "Vòng 4",
      description: "Phỏng vấn với HR và quản lý cấp cao để đánh giá văn hóa công ty và thương lượng điều kiện",
      order: 4,
      totalTime: 45,
      departmentModel: null,
      interviewTypeModel: null,
      id: "c702e19f-38cc-4b2d-8af7-08dde0ba28f4",
      creationDate: "2025-08-21T15:42:37.2561443Z",
      createdById: null,
      modificationDate: null,
      modifiedById: null,
      deletionDate: null,
      deletedById: null,
      isDeleted: false,
    },
    {
      stageName: "Vòng 5",
      description: "Phỏng vấn với HR và quản lý cấp cao để đánh giá văn hóa công ty và thương lượng điều kiện",
      order: 5,
      totalTime: 45,
      departmentModel: null,
      interviewTypeModel: null,
      id: "c702e19f-38cc-4b2d-8af7-08dde0ba28f4",
      creationDate: "2025-08-21T15:42:37.2561443Z",
      createdById: null,
      modificationDate: null,
      modifiedById: null,
      deletionDate: null,
      deletedById: null,
      isDeleted: false,
    },
  ],
  departmentId: "37d84d41-1ffc-43e5-d2de-08dddffc9a87",
  processName: "Quy trình tuyển dụng Developer",
  description: "Quy trình phỏng vấn toàn diện cho vị trí lập trình viên, bao gồm đánh giá kỹ năng và phù hợp văn hóa",
  departmentName: "Công Nghệ Thông Tin",
  countOfStage: 3,
  id: "052a1312-8eaa-43bc-d2df-08dddffc9a87",
  creationDate: "2025-08-21T15:37:22.3498614Z",
  createdById: null,
  modificationDate: null,
  modifiedById: null,
  deletionDate: null,
  deletedById: null,
  isDeleted: false,
}

export default function Page() {
  return (
    <main className="min-h-screen bg-background">
      <InterviewProcessDetail data={sampleData} />
    </main>
  )
}
