import type React from "react"
// import ClientLayout from "./clientLayout"

export const metadata = {
  title: "HRM AI",
  description: "Generated by create next app",
  generator: 'GSU25SE03',
  icons: {
    icon: [
      { url: "/meta_img.png", type: "image/png" },     // Default icon
      { url: "/meta_img.png", type: "image/jpeg" },    // Alternative icon
    ],
    shortcut: ["/meta_img.png"],              // Optional
    apple: ["/meta_img.png"],              // For iOS
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>
    <RouteTransitionOverlay />  
    <ToastProvider />
            <Suspense
              fallback={
                null
              } /* Mình dùng App Router nó sẽ tự động gọi đến app/loading.tsx */
            >
              {/* <Header/> */}
              {children}
              {/* <Footer/> */}
            </Suspense>
    </ClientLayout>
}


import '../globals.css'
import ClientLayout from "../clientLayout"
import { ToastProvider } from "@/components/toast/toast-provider"
import { Suspense } from "react"
import RouteTransitionOverlay from "@/components/route-transition-overlay"

