import type React from "react"
// import ClientLayout from "./clientLayout"

export const metadata = {
  title: "HRM AI",
  description: "Generated by create next app",
    generator: 'GSU25SE03'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>
    <RouteTransitionOverlay />  
    <ToastProvider />
            <Suspense
              fallback={
                null
              } /* Mình dùng App Router nó sẽ tự động gọi đến app/loading.tsx */
            >
              {/* <Header/> */}
              {children}
              {/* <Footer/> */}
            </Suspense>
    </ClientLayout>
}


import '../globals.css'
import ClientLayout from "../clientLayout"
import { ToastProvider } from "@/components/toast/toast-provider"
import { Suspense } from "react"
import RouteTransitionOverlay from "@/components/route-transition-overlay"

